#!/usr/bin/env python3
"""Fit a 3D ellipsoid and emit AngleReader MAG_A / MAG_B constants."""

import argparse
import csv
import sys
from pathlib import Path

try:
    import numpy as np
    import matplotlib.pyplot as plt
except ImportError:
    sys.exit("Fehler: numpy/matplotlib fehlen. Installieren mit: "
             "python3 -m pip install -r scripts/requirements-angle-tools.txt")


def load_points(path):
    with path.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream))
    names = ("mag_raw_x", "mag_raw_y", "mag_raw_z")
    if not rows or any(name not in rows[0] for name in names):
        sys.exit("Fehler: CSV benötigt mag_raw_x, mag_raw_y und mag_raw_z.")
    try:
        points = np.asarray([[float(row[name]) for name in names] for row in rows])
    except ValueError as exc:
        sys.exit(f"Fehler: ungültiger Magnetometerwert: {exc}")
    points = points[np.all(np.isfinite(points), axis=1)]
    if len(points) < 500:
        sys.exit(f"Fehler: nur {len(points)} gültige Punkte; mindestens 500 benötigt.")
    return points


def fit_ellipsoid(points):
    x, y, z = points.T
    design = np.column_stack((
        x*x, y*y, z*z, 2*x*y, 2*x*z, 2*y*z, x, y, z, np.ones(len(points))))
    _, _, vh = np.linalg.svd(design, full_matrices=False)
    p = vh[-1]
    m = np.array([[p[0], p[3], p[4]],
                  [p[3], p[1], p[5]],
                  [p[4], p[5], p[2]]])
    linear = p[6:9]
    constant = p[9]
    if np.linalg.det(m) < 0:
        m, linear, constant = -m, -linear, -constant
    center = -0.5 * np.linalg.solve(m, linear)
    scale = center @ m @ center - constant
    normalized = m / scale
    eigenvalues, eigenvectors = np.linalg.eigh(normalized)
    if np.any(eigenvalues <= 0):
        raise ValueError("Fit ist kein geschlossenes Ellipsoid; alle Achsen abdecken.")
    # Preserve a physical microtesla scale: median centered radius approximates
    # the local field magnitude. EKF only uses direction, but runtime gates use µT.
    target_radius = float(np.median(np.linalg.norm(points - center, axis=1)))
    correction = target_radius * (
        eigenvectors @ np.diag(np.sqrt(eigenvalues)) @ eigenvectors.T)
    corrected = (correction @ (points - center).T).T
    return center, correction, corrected, target_radius


def main():
    parser = argparse.ArgumentParser(
        description="Hard-/Soft-Iron-Ellipsoidfit aus Diagnose-CSV.")
    parser.add_argument("csv_file", type=Path)
    parser.add_argument("--output-dir", type=Path, default=Path("mag_calibration"))
    # Dolle und Hub teilen sich seit der MAC-Tabelle dasselbe Ausgabeformat,
    # ein --target braucht es nicht mehr. Das Argument wird noch angenommen und
    # ignoriert, damit ältere Notizen und Doku-Kommandozeilen nicht brechen.
    parser.add_argument(
        "--target", choices=("oarlock", "boat"), default=None,
        help=argparse.SUPPRESS)
    args = parser.parse_args()
    points = load_points(args.csv_file)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    try:
        center, matrix, corrected, radius = fit_ellipsoid(points)
    except (ValueError, np.linalg.LinAlgError) as exc:
        sys.exit(f"Fehler: Ellipsoidfit fehlgeschlagen: {exc}")

    corrected_norm = np.linalg.norm(corrected, axis=1)
    residual = np.std(corrected_norm) / np.mean(corrected_norm)
    spans = np.ptp(points, axis=0)
    coverage_ratio = np.min(spans) / np.max(spans)
    if coverage_ratio < 0.35:
        sys.exit("Fehler: 3D-Abdeckung unzureichend. Sensor um alle drei Achsen taumeln; "
                 f"Spannenverhältnis ist nur {coverage_ratio:.3f}.")
    if residual > 0.08:
        sys.exit("Fehler: Fit-Residuum ist zu groß "
                 f"({residual * 100:.2f} %). Magnetische Störer entfernen und wiederholen.")

    # Druckfertiger mag-Block für einen Eintrag in der Einheitentabelle in
    # lib/UnitIdentity/UnitIdentity.cpp. Dort nur den mag-Block der betroffenen
    # MAC ersetzen — keine andere Datei anfassen.
    lines = [
        "// Generated by scripts/calibrate_magnetometer.py",
        f"// {args.csv_file.name}, Residuum {residual * 100:.2f} %, "
        f"Feldbetrag {radius:.1f} uT, Spannenverhaeltnis {coverage_ratio:.3f}",
        "{",
        "    true,",
        "    {",
    ]
    for row in matrix:
        lines.append("        {" + ", ".join(f"{value:.9g}f" for value in row) + "},")
    lines += [
        "    },",
        "    {" + ", ".join(f"{value:.9g}f" for value in center) + "},",
        "},",
    ]
    output = "\n".join(lines) + "\n"
    (args.output_dir / "mag_calibration_constants.txt").write_text(output, encoding="utf-8")

    print(f"Punkte: {len(points)}")
    print(f"Zielfeldbetrag: {radius:.3f} uT")
    print(f"Residuum (std/mean): {residual * 100:.3f} %")
    print(f"3D-Spannenverhältnis: {coverage_ratio:.3f}")
    print(output)

    fig = plt.figure(figsize=(12, 5))
    before = fig.add_subplot(121, projection="3d")
    after = fig.add_subplot(122, projection="3d")
    stride = max(1, len(points) // 3000)
    before.scatter(*points[::stride].T, s=2)
    before.set_title("Rohdaten")
    after.scatter(*corrected[::stride].T, s=2)
    after.set_title("Korrigiert")
    for axis in (before, after):
        axis.set_xlabel("X")
        axis.set_ylabel("Y")
        axis.set_zlabel("Z")
    fig.tight_layout()
    fig.savefig(args.output_dir / "mag_point_cloud.png", dpi=150)
    plt.close(fig)


if __name__ == "__main__":
    main()
